### ISSUE TITLE
MalformedXmlException.php line 39 - Class "DOMDocument" not found

### ISSUE THREAD

**Issue by wassi007** [eliashaeussler/cache-warmup#314] opened 2023-12-08 21:18 UTC
### PHP version

8.1.2

### Package version

2.7.0

### Application

Phar

### Operating system

Ubuntu 22.04

### Current behavior

./cache-warmup.phar https://google.com/sitemap.xml
Running cache warmup 2.7.0 by Elias Häußler and contributors.
Parsing sitemaps... 
In MalformedXmlException.php line 39:
                                                                                                                            
  The string "<?xml version="1.0" encoding="UTF-8"?>                                                                        
  <sitemapindex xmlns="http://www.google.com/schemas/sitemap/0…" does not contain valid XML: Class "DOMDocument" not found  

The same Message with Docker

### Additional context

Does anyone have an idea what the problem could be? 
I tested several sitemaps, but always the same error.
The same result with Docker containers.

**Comment by eliashaeussler** [comment] 2024-01-09 21:39
Hi @wassi007, the message `Class "DOMDocument" not found` usually indicates that the `ext-dom` library is not installed in your environment. Read for example https://stackoverflow.com/questions/14395239/class-domdocument-not-found to learn how to properly install it.

For the Docker part, it would be interesting what command you actually executed. Please share the command for further investigation.

Unfortunately, I cannot reproduce the issue, neither by using the Phar file nor by using Docker.

**Comment by eliashaeussler** [comment] 2024-02-06 20:26
I'm closing this issue for now. If the issue persists, feel free to write back.

**Closed by eliashaeussler** 2024-02-06 20:26 UTC
Labels: bug
